version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: movie-rec-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: movie_recommendation_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - movie-rec-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: movie-rec-backend
    restart: unless-stopped
    environment:
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/movie_recommendation_db?authSource=admin
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ENVIRONMENT=development
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - ./ml:/app/ml
    networks:
      - movie-rec-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movie-rec-frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - movie-rec-network

volumes:
  mongodb_data:

networks:
  movie-rec-network:
    driver: bridge
